### ISSUE TITLE
API Key in train.py

### ISSUE THREAD

**Issue by fabienmorgan** [1716757342/MMSR#2]
I would suggest you to remove the API Key of Weights & Biases in the [train.py](https://github.com/1716757342/MMSR/blob/main/MMSR/train.py) file. This key should not be known to the public.

**Comment by 1716757342** [comment]
Thank you for your reminder, we have taken care of it. Wishing you a pleasant life.

**Comment by fabienmorgan** [comment]
I don't think the issue has been. Firstly, the API Key still can be found in the git history [train.py](https://github.com/1716757342/MMSR/commit/81f64016f62f10b03627b4559aa85cec6edfefa8). Secondly, you need to remove or comment out the whole line and can't just remove the string. Else `os.environ["WANDB_API_KEY"]` and `os.environ["WANDB_MODE"]` get assigned to nothing, which returns this error: 
Traceback (most recent call last):
  ```
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/fmg/repos/FMg_SR_Bachelor_Thesis/Original_MMSR/MMSR/__main__.py", line 10, in <module>
    from .train import train as train
  File "/home/fmg/repos/FMg_SR_Bachelor_Thesis/Original_MMSR/MMSR/train.py", line 4
    os.environ["WANDB_API_KEY"]  = 
                                  ^
SyntaxError: invalid syntax
```
